### ISSUE TITLE
Simple generic "user guide"

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#343]
We need to properly document how to manually deploy and verify both ClusterIP and headless services. This info is mostly hidden today behind the automated verifications steps, which makes it hard for users to understand what's going on.

**Comment by LaumiH** [comment]
What I am missing: a guide for "what do I need to do to get a very simple Submariner deployment working". I read the [deployment docs](https://submariner.io/deployment/) and it stopped at joining the clusters. I was like: and what do I do then? Is this it? How do I address Services across clusters, do I need to do anything in order to make them discoverable, or do all Services get exposed automatically? Do I even want this?

What is also new to me is that there needs to be one node with the `submariner.io/gateway: "true"` annotation, would be great if this was in the docs, or does it happen automatically?

**Comment by LaumiH** [comment]
What I would also add: which firewall rules do I need to apply? :) 
Are `--allow=udp:4800 --allow=udp:4500 --allow=udp:500` correct?

**Comment by LaumiH** [comment]
I hope it is ok that I just add more and more of what I notice while experimenting with Submariner :)
Just noticed: k8s version 1.17 or higher is needed, at least my GKE nodes were too old.

**Comment by nyechiel** [comment]
Cool @LaumiH. Please keep adding feedback in here and we will address it 👍

**Comment by LaumiH** [comment]
What I am missing right now is some info about the supporting companies of Submariner. Are there any companies actively contributing, or is it something you do on your free time etc.? I hope my idea/inquiry is understandable.

**Comment by nyechiel** [comment]
> What I am missing right now is some info about the supporting companies of Submariner. Are there any companies actively contributing, or is it something you do on your free time etc.? I hope my idea/inquiry is understandable.

Hi @LaumiH. Submariner is an open-source project and we welcome all contributors and users! Currently, we have contributors from (mostly) Rancher, Red Hat, IBM, and Hitachi and our goal is to move the project into the CNCF.

**Comment by LaumiH** [comment]
I just wanted to add the problem I faced recently (we discussed this on Slack): 
I did not know that I had to create all namespaces and services I want to export via Submariner in all clusters. 
My pods in the remote cluster were not able to resolve the DNS names of the local cluster, just because I did not have the same namespaces and services in both clusters.
See sig-multicluster/namespace-sameness-position-statement.md
