### ISSUE TITLE
Document the Markdown linting requirements

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/submariner-website#353]
At the minimum we need to clearly document that our linting enforces a maximum line length of 140.

/cc @dfarrell07

**Comment by dfarrell07** [comment]
We currently say: 

"See the linter configuration files at the root of each repository for details about which checks are enabled."

https://submariner.io/contributing/building_testing/#linting

And each repo has

```
# Set maximum line Length to 140c to match Go linting
line-length:
  line_length: 140
```

https://github.com/submariner-io/submariner-website/blob/master/.markdownlint.yml

If folks break the linter, I think the problem is pretty clear (clearly named job, clear/actionable error message).

We don't document other linting requirements, and I generally think of linting as in part "automated documentation of norms".

So I tend to think we shouldn't document this more explicitly.

**Comment by nyechiel** [comment]
@dfarrell07 oh I did not know we have this documented, thanks. I guess we should link it somehow to https://submariner.io/contributing/website/ which is the place I went to intuitively?
