### ISSUE TITLE
Document using Prometheus on KIND setup

### ISSUE THREAD

**Issue by Jaanki** [submariner-io/submariner-website#493]

**Comment by nyechiel** [comment]
This is not user facing IMHO (i.e shouldn't be in the quickstart guide), but maybe can be included in one of the sections of the developer guide. 

FWIW, here is how I tested Prometheus with kind:

1. Deploy with `make deploy using=prometheus` or with `make clusters using=prometheus`. This will deploy the latest Prometheus on each kind cluster: `kubectl describe svc prometheus-operator -n submariner-operator`

2. Configure port-forward in order to to access the internal Kubernetes cluster/service, for e.g `kubectl --context=cluster2 port-forward service/prometheus-operated 9090 &`

3. UI should be accessible in http://localhost:9090/graph

**Comment by nyechiel** [comment]
Closing this for now. I don't think it's something common that users are ever going to run outside of CI, etc.
