### ISSUE TITLE
Add documentation for using cable driver VXLAN

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/submariner-website#597]

**Comment by nyechiel** [comment]
@maayanf24 This is currently documented as part of `subctl join` here: https://submariner.io/operations/deployment/subctl/#join-flags-general. Did you have something else in mind?

**Comment by maayanf24** [comment]
> @maayanf24 This is currently documented as part of `subctl join` here: https://submariner.io/operations/deployment/subctl/#join-flags-general. Did you have something else in mind?

@aswinsuryan mentioned that the recommended deployments is with NAT disabled , and advice to use VPC network peering. Those recommendations are not documented.

**Comment by nyechiel** [comment]
@maayanf24 @aswinsuryan can you please look at our docs and see where we can mention that? maybe under https://submariner.io/getting-started/architecture/gateway-engine/?

**Comment by nyechiel** [comment]
This came up in a few conversations lately, so I wanted to summarize some key points we need to document:

- The Submariner provided VXLAN connections are unencrypted by design. This is typically useful for ClusterSets environments in which all of the participating clusters run on-premises and the underlying inter-network fabric is controlled by the admin (and in many cases already encrypted by other means).

- Other common use case is to leverage the VXLAN driver on top of VPC Peering connections on public clouds. In this case, the VXLAN connection will be established on top of a VPC Peering link which is provided by the underlying cloud infrastructure (and is already encrypted). An example of such case can be found here: https://cloud.redhat.com/blog/geographically-distributed-stateful-workloads-part-four-kafka 

We have started to look at what it would take to automate the VPC Peering creation, see: https://github.com/submariner-io/submariner-operator/issues/1642 

/cc @sridhargaddam @vthapar
